### ISSUE TITLE
Syntax/Semantic highlighting

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#105]
**Tasks**
- [x] Refactor TextMate grammar to comply with the Ballerina spec
- [x] Add tests for TextMate grammar
- [x] Add semantic highlighting
- [x] Add tests for semantic highlighting

|        Issue          | Require semantic highlighting |
| ------------- | ------------- |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/3</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/21</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/22</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/23</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/33</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/35</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/37</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/38</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/39</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/40</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/41</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/42</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/69</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/77</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/96</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/98</li></ul> | <ul><li> [x] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/102</li></ul> | <ul><li> [ ] </li></ul> |
| <ul><li>[x] https://github.com/wso2/ballerina-plugin-vscode/issues/104</li></ul> | <ul><li> [ ] </li></ul> |

**Suggested Labels:**

**Suggested Assignees:**

@gigara @prabushi

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
- [ ] Test the monarch json changes
- [ ] Check prism changes
- [ ] Test changes with https://github.com/jclark/semtype and update fixes

**Comment by prabushi** [comment]
TextMate grammar test updates were carried out in https://github.com/wso2/ballerina-plugin-vscode/issues/115
