### ISSUE TITLE
 Ballerina VS Code 2.5.0 Release

### ISSUE THREAD

**Issue by hevayo** [wso2/ballerina-plugin-vscode#117]
**Description:**
Following is the task list for 2.5.0 release of the plugin. The plugin will support Graphical editing and Choreo Integration. 

Milestone 1
- [x] Graphical editing
- [x] Central Connector API integration 

Milestone 2
- [x] Test API implementation https://github.com/wso2/ballerina-plugin-vscode/issues/119
- [x] Ballerina Tab for VSCode https://github.com/wso2/ballerina-plugin-vscode/issues/118
- [x] LS capability registration https://github.com/wso2/ballerina-plugin-vscode/issues/91
- [x] Authentication with Choreo APIs
- [ ] Data Collection Pipeline for Observability

Milestone 3
- [x] Performance Forecasting with Choreo API
- [ ] AI assisted Form filling with Choreo API
- [x] Ballerina Semantic Highlighting https://github.com/wso2/ballerina-plugin-vscode/issues/109
- [x] https://github.com/wso2/ballerina-plugin-vscode/issues/97
- [x] Try it capability for Ballerina HTTP services

**Issues**

**Comment by prabushi** [comment]
This task is done. Released 3.0.0 on 28/01/2022.
