### ISSUE TITLE
Ballerina Notebook 

### ISSUE THREAD

**Issue by HirumalPriyashan** [wso2/ballerina-plugin-vscode#183]
**Description:**
Ballerina notebook which enables Ballerina shell and Ballerina CLI capabilities.

**Tasks**

- [x] Define the Ballerina notebook file extension
- [x] Define the Ballerina VS Code experience
- [x] Notebook API integration with the Ballerina VS Code extension
- [x] Implement notebook serializer 
- [x] Implement notebook controller
- Ballerina Shell integration via Language Server extended APIs
  - [x] Implement Language Server expended APIs
  - [x] Implement tests for the LS extension
  - [x] Integrate with VSCode Language Server client
- Custom output renderer support
  - [x] Plain Text - string, int, boolean, float, byte
  - [x] Table view
  - [x] Json view
  - [x] Xml view
  - [x] Ballerina Record
- Language support
  - [x] Code Completion
  - [x] Syntax highlighting
- [x] Variables panel
- [x] View outline
- [x] Restart capability for the notebook
- [x] Ballerina debugger integration
- [x] Ballerina CLI integration
- [x] Implement tests for the notebook implementation
- [x] Provide support for variable deletion from notebook
- [x] Feature documentation

**Comment by HirumalPriyashan** [comment]
**Code Completions**

Code completions are available in Ballerina notebooks.

**Implementation Details**
Ballerina Notebook cells use `vscode-notebook-cell` as their scheme type in Uris. Since Ballerina Compiler does not provide support for `vscode-notebook-cell` scheme type or in-memory source streams, the temporary `.bal` file created by Ballerina Shell has been used to provide completions. Another temporary `.bal` file will be created using the content shell `.bal` file which will change according to changes in notebook cell and details of positions and Uri details are used to get code completions from the Ballerina language Server.

**Comment by HirumalPriyashan** [comment]
**Limitations**

- Support for code completions are limited due to Ballerina language not providing support for in-memory source streams.
https://github.com/ballerina-platform/ballerina-lang/issues/35367 

Limitations associated with Ballerina Shell will also be limitations for Ballerina Notebook. Once those are resolved with Ballerina Shell those will be resolved for Ballerina Notebook too.
- Limitations with function names such as `main` and `init`.
https://github.com/ballerina-platform/ballerina-lang/issues/30923 
- Ballerina Shell currently does not support services.
https://github.com/ballerina-platform/ballerina-lang/issues/30916 
- Ballerina Shell does not support configurables,but default configurables are available.
https://github.com/ballerina-platform/ballerina-lang/issues/28662 
- Unexpected runtime errors in Ballerina Shell.
https://github.com/ballerina-platform/ballerina-lang/issues/31922
- Current Ballerina Shell can’t support the isolation concept.
https://github.com/ballerina-platform/ballerina-lang/issues/31828 
- Does not provide stack trace for panics.
https://github.com/ballerina-platform/ballerina-lang/issues/30914

**Comment by HirumalPriyashan** [comment]
**Notebook debugger**

After enabling the `Notebook Debug Mode` from configurations, a notebook can be debug using the button in the drop down menu near the `▷` (Run Cell) button.

**Implementation details**
Since it is required to compile a source file, to support debugging in the notebook, a temporary `.bal` file is used.

All the successfully ran cells' content which are above the cell that ran the debug will be in the module level of the temporary `.bal` file, and the content of the cell which ran debug will put inside the main function of the `.bal` file.

Finally, requests send to the debug adapter by VS Code and responses coming from debug adapter to VS Code will be mapped from cell to line in temporary `.bal` file and from line in temporary `.bal` file to cell respectively using `DebugAdapterTracker` which manipulates the requests and responses accordingly.
